# Generated by Django 2.2.4 on 2020-01-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20200121_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Profile',
        ),
    ]
