# Generated by Django 2.2.4 on 2020-01-21 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0006_city_offer_service_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0004_delete_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Date of Birth', models.DateField()),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
