# Generated by Django 2.2.4 on 2020-02-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_auto_20200229_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='image',
            field=models.ImageField(null=True, upload_to='Customers/'),
        ),
    ]
