# Generated by Django 2.2.4 on 2020-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_auto_20200303_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='image',
            field=models.ImageField(default='user-default.jpg', null=True, upload_to='Customers/'),
        ),
    ]
