# Generated by Django 2.2.4 on 2020-03-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_auto_20200303_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_profile',
            name='DOB',
        ),
    ]
