# Generated by Django 2.2.4 on 2020-01-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Service ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Service Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
    ]
