# Generated by Django 2.2.4 on 2020-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Offer From', models.DateField()),
                ('Offer To', models.DateField()),
                ('Discount Ratio', models.IntegerField()),
                ('Maximum Amount', models.IntegerField()),
            ],
        ),
    ]
