# Generated by Django 2.2.4 on 2020-01-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Discount Ratio',
            new_name='disc_ratio',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='Maximum Amount',
            new_name='maxamount',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='Offer From',
            new_name='offer_from',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='Offer To',
            new_name='offer_to',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Service ID',
            new_name='ser_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Service Name',
            new_name='ser_name',
        ),
    ]
