# Generated by Django 2.2.4 on 2020-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_city_offer_service_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ser_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
