# Generated by Django 2.2.4 on 2020-02-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200204_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
