# Generated by Django 2.2.4 on 2020-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200214_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
