# Generated by Django 2.2.4 on 2020-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20200214_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='Posters/'),
        ),
    ]
