# Generated by Django 2.2.4 on 2020-02-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_state_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='poster',
        ),
        migrations.AddField(
            model_name='service',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='Posters/'),
        ),
    ]
