# Generated by Django 2.2.4 on 2020-01-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceProvider', '0012_auto_20200121_2024'),
        ('Customer', '0005_customer_profile'),
        ('Home', '0006_city_offer_service_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('ap_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bdate', models.DateTimeField()),
                ('aptime', models.DateTimeField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Offer')),
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.OperatorProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate', models.CharField(max_length=1)),
                ('ap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.Appointment')),
            ],
        ),
    ]
