# Generated by Django 2.2.4 on 2020-02-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_auto_20200123_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='aptime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='at_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='op_id',
        ),
    ]
