# Generated by Django 2.2.4 on 2020-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_auto_20200204_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ap_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
