# Generated by Django 2.2.4 on 2020-02-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0026_operatorprofile_uname'),
        ('Appointments', '0006_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='adate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReserveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField()),
                ('os_id', models.ManyToManyField(to='ServiceProvider.OperatorService')),
            ],
        ),
    ]
