# Generated by Django 2.2.4 on 2020-02-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0009_auto_20200206_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='adate',
        ),
    ]
