# Generated by Django 2.2.4 on 2020-02-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0010_remove_appointment_adate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ap_id',
        ),
    ]
