# Generated by Django 2.2.4 on 2020-02-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0011_remove_feedback_ap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ap_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Appointments.Appointment'),
            preserve_default=False,
        ),
    ]
