# Generated by Django 2.2.4 on 2020-02-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0012_feedback_ap_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReserveLog',
        ),
    ]
