# Generated by Django 2.2.4 on 2020-02-06 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0026_operatorprofile_uname'),
        ('Appointments', '0013_delete_reservelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='adate',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 6)),
        ),
        migrations.CreateModel(
            name='ReserveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('os_id', models.ManyToManyField(to='ServiceProvider.OperatorService')),
            ],
        ),
    ]
