# Generated by Django 2.2.4 on 2020-02-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0015_auto_20200214_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='offer',
        ),
    ]
