# Generated by Django 2.2.4 on 2020-02-16 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0017_appointment_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='adate',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 16)),
        ),
    ]
