# Generated by Django 2.2.4 on 2020-02-29 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0019_auto_20200225_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='adate',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 29)),
        ),
    ]
