# Generated by Django 2.2.4 on 2020-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0021_auto_20200303_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservelog',
            name='os_id',
        ),
        migrations.AddField(
            model_name='reservelog',
            name='os_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
