# Generated by Django 2.2.4 on 2020-03-04 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0022_auto_20200303_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='adate',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 4)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='bdate',
            field=models.DateField(),
        ),
    ]
