# Generated by Django 2.2.4 on 2020-01-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('at_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Attendant Name', models.CharField(max_length=50)),
                ('First Name:', models.CharField(max_length=30)),
                ('Last Name:', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=1)),
                ('Image', models.ImageField(upload_to='')),
                ('Description', models.TextField()),
                ('ser_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.OperatorProfile')),
            ],
        ),
    ]
