# Generated by Django 2.2.4 on 2020-01-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_service'),
        ('ServiceProvider', '0002_attendant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorService',
            fields=[
                ('Unique ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Time From', models.TimeField()),
                ('Time To', models.TimeField()),
                ('Decimal Value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Is Reserved', models.BooleanField()),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.Attendant')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.OperatorProfile')),
                ('ser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Service')),
            ],
        ),
    ]
