# Generated by Django 2.2.4 on 2020-01-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0003_operatorservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorprofile',
            old_name='Firm Name:',
            new_name='firm_name',
        ),
    ]
