# Generated by Django 2.2.4 on 2020-01-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0004_auto_20200113_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorprofile',
            old_name='Contact',
            new_name='contact',
        ),
    ]
