# Generated by Django 2.2.4 on 2020-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0005_auto_20200113_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorprofile',
            old_name='Address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='attendant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operatorservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
