# Generated by Django 2.2.4 on 2020-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0007_auto_20200121_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorservice',
            name='Decimal Value',
        ),
        migrations.AddField(
            model_name='operatorservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
