# Generated by Django 2.2.4 on 2020-01-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0008_auto_20200121_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorservice',
            name='ser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Service', to_field='Service ID'),
        ),
    ]
