# Generated by Django 2.2.4 on 2020-01-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0009_auto_20200121_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorservice',
            old_name='Is Reserved',
            new_name='is_res',
        ),
        migrations.RenameField(
            model_name='operatorservice',
            old_name='Unique ID',
            new_name='op_ser',
        ),
        migrations.RenameField(
            model_name='operatorservice',
            old_name='Time From',
            new_name='time_from',
        ),
        migrations.RenameField(
            model_name='operatorservice',
            old_name='Time To',
            new_name='time_to',
        ),
        migrations.AlterField(
            model_name='operatorservice',
            name='ser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Service'),
        ),
    ]
