# Generated by Django 2.2.4 on 2020-01-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0010_auto_20200121_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='operatorprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='operatorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operatorservice',
            name='attendant',
        ),
        migrations.RemoveField(
            model_name='operatorservice',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='operatorservice',
            name='ser_id',
        ),
        migrations.DeleteModel(
            name='Attendant',
        ),
        migrations.DeleteModel(
            name='OperatorProfile',
        ),
        migrations.DeleteModel(
            name='OperatorService',
        ),
    ]
