# Generated by Django 2.2.4 on 2020-01-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0012_auto_20200121_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='lname',
        ),
    ]
