# Generated by Django 2.2.4 on 2020-01-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0013_auto_20200123_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='contact',
            field=models.CharField(default='8128256987', max_length=10),
            preserve_default=False,
        ),
    ]
