# Generated by Django 2.2.4 on 2020-01-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0014_attendant_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
