# Generated by Django 2.2.4 on 2020-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0015_auto_20200123_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='media/Service Providers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendant',
            name='image',
            field=models.ImageField(upload_to='media/Attendants'),
        ),
    ]
