# Generated by Django 2.2.4 on 2020-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0016_auto_20200123_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='media/Service Providers'),
        ),
    ]
