# Generated by Django 2.2.4 on 2020-01-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0018_auto_20200124_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='image',
            field=models.ImageField(upload_to='Attendants/'),
        ),
    ]
