# Generated by Django 2.2.4 on 2020-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0019_auto_20200124_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorservice',
            name='bio',
            field=models.TextField(default='One and only authentic salon in the town'),
            preserve_default=False,
        ),
    ]
