# Generated by Django 2.2.4 on 2020-02-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0023_auto_20200204_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='Service Providers/'),
        ),
    ]
