# Generated by Django 2.2.4 on 2020-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0024_auto_20200204_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='at_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorservice',
            name='op_ser',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
