# Generated by Django 2.2.4 on 2020-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0025_auto_20200204_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='uname',
            field=models.CharField(default='USER', max_length=30),
        ),
    ]
