# Generated by Django 2.2.4 on 2020-02-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0026_operatorprofile_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='joined_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
