# Generated by Django 2.2.4 on 2020-02-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0028_auto_20200216_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorservice',
            name='is_res',
        ),
    ]
