# Generated by Django 2.2.4 on 2020-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0029_remove_operatorservice_is_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='image',
            field=models.ImageField(default='user-default.jpg', upload_to='Attendants/'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='image',
            field=models.ImageField(blank=True, default='user-default.jpg', upload_to='Service Providers/'),
        ),
    ]
